# Generated by Django 4.0.1 on 2022-01-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_alter_film_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='description_title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
