# Generated by Django 4.0.1 on 2022-01-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_film_description_film_description_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='description',
        ),
        migrations.RemoveField(
            model_name='film',
            name='description_title',
        ),
    ]
