# Generated by Django 4.0.1 on 2022-01-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='updated_date',
        ),
    ]
