# Generated by Django 4.0.1 on 2022-01-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_bookscomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=13)),
                ('last_name', models.CharField(max_length=13)),
                ('surname', models.CharField(max_length=13)),
                ('job_expert', models.CharField(choices=[('Программист', 'Программист'), ('Юморист', 'Юморист'), ('Электрик', 'Электрик'), ('Дипломат', 'Дипломат'), ('Таксист', 'Таксист'), ('Анимешник', 'Анимешник')], max_length=100)),
                ('info_about_expert', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertRecomendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendation_book', models.TextField(max_length=250)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expert_Recomendation', to='book.book')),
                ('expert1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_expert', to='book.expert')),
            ],
        ),
    ]
