# Generated by Django 4.0.1 on 2022-01-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_expert_expertrecomendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertrecomendation',
            name='created_date',
        ),
        migrations.AddField(
            model_name='expertrecomendation',
            name='created_date_expert',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='job_expert',
            field=models.CharField(choices=[('Proger', 'Proger'), ('Юморист', 'Юморист'), ('Электрик', 'Электрик'), ('Дипломат', 'Дипломат'), ('Таксист', 'Таксист'), ('Анимешник', 'Анимешник')], max_length=100),
        ),
    ]
