# Generated by Django 4.0.1 on 2022-01-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_expertrecomendation_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertrecomendation',
            old_name='expert',
            new_name='book',
        ),
    ]
