# Generated by Django 4.0.1 on 2022-01-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_rename_expert_expertrecomendation_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='surname',
        ),
        migrations.AddField(
            model_name='expert',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
