# Generated by Django 4.0.1 on 2022-01-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_remove_expert_first_name_remove_expert_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertrecomendation',
            old_name='expert1',
            new_name='expert',
        ),
    ]
